/*
 * Propriedade intelectual: Luís Rodrigo da Costa
 * Com apoio: IA Chatgpt/Codex que atende por nome: Sophia
 * Sistema de gestão: GenesisGest.Net
 * Ano Início: 04/2024 Publicado e operacional: 05/2026
 * Versão: 1.1.5
 */
// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexumAltivon.API.ERP.SharedData;

#nullable disable

namespace NexumAltivon.API.ERP.SharedData.Migrations
{
    [DbContext(typeof(GenesisDbContext))]
    [Migration("20260705114438_InitialGenesis")]
    partial class InitialGenesis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NexumAltivon.API.ERP.SharedData.GenesisBoleto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Banco")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("banco");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("codigo_barras");

                    b.Property<int>("ContaReceberId")
                        .HasColumnType("int")
                        .HasColumnName("conta_receber_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("criado_em");

                    b.Property<string>("LinhaDigitavel")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("linha_digitavel");

                    b.Property<string>("NossoNumero")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nosso_numero");

                    b.Property<string>("PdfUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("pdf_url");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<string>("UrlBoleto")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("url_boleto");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("vencimento");

                    b.HasKey("Id");

                    b.ToTable("erp_boletos");
                });

            modelBuilder.Entity("NexumAltivon.API.ERP.SharedData.GenesisContaPagar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_emissao");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_pagamento");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_vencimento");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descricao");

                    b.Property<string>("FormaPagamento")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("forma_pagamento");

                    b.Property<int?>("FornecedorId")
                        .HasColumnType("int")
                        .HasColumnName("fornecedor_id");

                    b.Property<string>("NumeroBoleto")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("numero_boleto");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("numero_documento");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor_desconto");

                    b.Property<decimal>("ValorJuros")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor_juros");

                    b.Property<decimal>("ValorMulta")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor_multa");

                    b.Property<decimal>("ValorOriginal")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor_original");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor_pago");

                    b.HasKey("Id");

                    b.ToTable("erp_contas_pagar");
                });

            modelBuilder.Entity("NexumAltivon.API.ERP.SharedData.GenesisContaReceber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_emissao");

                    b.Property<DateTime?>("DataRecebimento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_recebimento");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_vencimento");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descricao");

                    b.Property<string>("FormaRecebimento")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("forma_recebimento");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("numero_documento");

                    b.Property<string>("NumeroPedidoReferencia")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("numero_pedido_referencia");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor_desconto");

                    b.Property<decimal>("ValorJuros")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor_juros");

                    b.Property<decimal>("ValorMulta")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor_multa");

                    b.Property<decimal>("ValorOriginal")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor_original");

                    b.Property<decimal>("ValorRecebido")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor_recebido");

                    b.HasKey("Id");

                    b.ToTable("erp_contas_receber");
                });

            modelBuilder.Entity("NexumAltivon.API.ERP.SharedData.GenesisFinanceReferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("descricao");

                    b.Property<int>("Ordem")
                        .HasColumnType("int")
                        .HasColumnName("ordem");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("erp_financeiro_referencias");
                });

            modelBuilder.Entity("NexumAltivon.API.ERP.SharedData.GenesisFluxoCaixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("categoria");

                    b.Property<string>("ContaBancaria")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("conta_bancaria");

                    b.Property<int?>("ContaPagarId")
                        .HasColumnType("int")
                        .HasColumnName("conta_pagar_id");

                    b.Property<int?>("ContaReceberId")
                        .HasColumnType("int")
                        .HasColumnName("conta_receber_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descricao");

                    b.Property<string>("FormaPagamento")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("forma_pagamento");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext")
                        .HasColumnName("observacoes");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.ToTable("erp_fluxo_caixa");
                });

            modelBuilder.Entity("NexumAltivon.API.ERP.SharedData.GenesisRhColaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("cargo");

                    b.Property<DateTime?>("DataAdmissao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_admissao");

                    b.Property<string>("Departamento")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("departamento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("erp_rh_colaboradores");
                });

            modelBuilder.Entity("NexumAltivon.API.ERP.SharedData.GenesisRhReferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("descricao");

                    b.Property<int>("Ordem")
                        .HasColumnType("int")
                        .HasColumnName("ordem");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("erp_rh_referencias");
                });
#pragma warning restore 612, 618
        }
    }
}
