upstream nexum_frontend {
    server nexum-frontend:80;
    keepalive 32;
}

upstream nexum_api {
    server nexum-api:8080;
    keepalive 32;
}

server {
    listen 80;
    server_name nexumaltivon.com www.nexumaltivon.com erp.nexumaltivon.com crm.nexumaltivon.com pdv.nexumaltivon.com admin.nexumaltivon.com localhost;

    location / {
        proxy_pass http://nexum_frontend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /health {
        proxy_pass http://nexum_frontend/health;
        access_log off;
    }
}

server {
    listen 80;
    server_name api.nexumaltivon.com back.nexumaltivon.com;

    location / {
        proxy_pass http://nexum_api;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;
    }

    location = /health {
        proxy_pass http://nexum_api/health;
        access_log off;
    }
}
